'use client';

import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { createContext } from 'react';

const notoSansJP400 = Noto_Sans_JP({
  weight: '400',
  display: 'swap',
  preload: false,
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// User型のエイリアスタイプ
type UserType = {
  name: string;
  age: number;
  hobby: string;
};

// Contextの初期値
const defaultUser: UserType = {
  name: 'Bob',
  age: 15,
  hobby: 'piano',
};

// Context作成
export const UserContext = createContext<UserType>(defaultUser);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserContext.Provider value={defaultUser}>
        <body
          className={notoSansJP400.className}
          suppressHydrationWarning={true}
        >
          <Header />
          {children}
          <Footer />
        </body>
      </UserContext.Provider>
    </html>
  );
}
